### ISSUE TITLE
Acccept input over stdin | pipe

### ISSUE THREAD

**Issue by felintusun** [dergecko/test-certs#1]
It would be helpful to accept input via stdin in situations where working with config files is impractical.
Is there a way to input a heredoc yaml via stdin instead of specifying an input file?

here is a incomplete example of how to invoke `test-certs` with a heredoc of the yaml config: 
```bash
cat << EOF | test-certs -
# Creates a root ca
my-root-ca:
  # the my-root-ca key file is by default not exported
  type: ca
  certificates:
EOF
```
the heredoc variant would be neat because the config.file stays the same.

any thoughts on this?  certainly there could be other ways to achieve fileless input.

**Comment by dergecko** [comment]
I had a look at it and could be achieved quite easily. 
That is definitely an interesting use case! 
Examples are in the README.
